"""Pin: SQLite-incompatible capability flags are declared False at class scope, not inherited,
so an upstream default flip can't silently emit DDL the dqlite cluster rejects."""

from __future__ import annotations

from sqlalchemydqlite.base import DqliteDialect


def test_supports_sequences_pinned_false() -> None:
    """SQLite (and dqlite) has no SEQUENCE primitive."""
    assert DqliteDialect.supports_sequences is False
    assert "supports_sequences" in DqliteDialect.__dict__


def test_supports_identity_columns_pinned_false() -> None:
    """SQLite uses INTEGER PRIMARY KEY AUTOINCREMENT, not
    SQL-standard GENERATED BY DEFAULT AS IDENTITY."""
    assert DqliteDialect.supports_identity_columns is False
    assert "supports_identity_columns" in DqliteDialect.__dict__


def test_preexecute_autoincrement_sequences_pinned_false() -> None:
    """SQLite-style AUTOINCREMENT is server-side; no pre-execute
    SELECT to fetch a next sequence value."""
    assert DqliteDialect.preexecute_autoincrement_sequences is False
    assert "preexecute_autoincrement_sequences" in DqliteDialect.__dict__
